name = "id1"
main = "worker.js"
compatibility_date = "2023-08-23"
routes = [
    	{ pattern = "zen.troy.my.id", custom_domain = true }, 
        { pattern = "support.zoom.us.zen.troy.my.id", custom_domain = true },
        ]
